eslint/rewrite

release-please-config.json
I think release-please is confused because we didn't tell it what commit to start from. Hopefully this will do the trick.
fixes #8
=> fix: Add bootstrap SHA to release-please config

.github/workflows/ci.yml, .github/workflows/release-please.yml, package.json, packages/config-array/jsr.json, packages/config-array/package.json, packages/config-array/src/base-schema.js, packages/config-array/src/config-array.js, packages/config-array/src/files-and-ignores-schema.js, packages/config-array/src/types.ts, packages/config-array/tsconfig.cjs.json, packages/object-schema/tsconfig.cjs.json, scripts/build.js, tools/dedupe-types.js
This adds type checking to the `config-array` package, generating types for both ESM and CJS.
=> feat: Add types to config-array

.github/workflows/release-please.yml
Fixes https://github.com/eslint/rewrite/issues/8
In GitHub actions, steps' output properties always have _string_ values.
Per https://github.com/google-github-actions/release-please-action/issues/912 and https://github.com/google-github-actions/release-please-action/pull/915, a breaking change in `release-please-action@v4` is that when there are no releases created, instead of omitting `releases_created` property it sets it to a truthy string `"false"`.
This PR updates the condition `if: ${{ steps.release.outputs.releases_created }}` to `if: ${{ steps.release.outputs.releases_created == 'true' }}` to avoid running unnecessary steps when there are no releases created.
=> build: avoid unnecessary steps in release-please workflow

packages/compat/jsr.json, packages/compat/package.json, packages/config-array/package.json, packages/object-schema/jsr.json, packages/object-schema/package.json
Updates `package.json` in all three packages to align them with changes from the last few commits.
* Packages should have `"access": "public"`, which allows publishing a scoped package as public.
* `files` explicitly lists files that should be published from `dist/` to avoid publishing `types.ts`. (the same change is done in `jsr.json` files).
* Packages should not have a `prepare` script.
=> feat: sync packages meta

packages/compat/CHANGELOG.md, packages/config-array/CHANGELOG.md, packages/object-schema/CHANGELOG.md
Previous release failed, so these are minor changes designed to trigger a new release for each package.
=> fix: Minor change to trigger new releases

README.md
Adds `@eslint/compat` to the list of packages in README.
=> docs: add `@eslint/compat` package to README

packages/config-array/src/config-array.js, packages/config-array/src/types.ts
This renames the `BaseConfigObject` interface to `ConfigObject` and allows for any number of other named properties. I think this better reflects the reality of the package.
=> fix: ConfigObject type

packages/config-array/src/config-array.js, packages/config-array/tests/config-array.test.js
This PR adds a method `getConfigStatus` to `ConfigArray` to determine the reason a file has no matching config. This could be used in ESLint to provide a better message for files that don't have a matching configuration. The reason could be:
* The file is ignored by global ignores patterns
* The file is outside the base path
* The file has no non-universal files pattern matching
There is also a new method `getConfigWithStatus` that returns a config object and the status for a file. This is now the backing implementation for both `getConfig` and `getConfigStatus`.
This PR also changes the behavior of the methods `isFileIgnored`/`isIgnored`. These methods will now only return `true` for files that are ignored due to ignores patterns. This is a breaking change.
Refs …
=> feat!: add method `getConfigStatus`, update `isFileIgnored`

.c8rc, packages/compat/package.json, packages/config-array/package.json, packages/object-schema/package.json
Add npm scripts to collect code coverage from tests. Run with `npm run test:coverage` in a package directory.
* Added a c8 config for the whole repo.
* Added c8 dependency and `test:coverage` script to each package.json file.
This should trigger a new release.
=> fix: add code coverage npm scripts

.github/workflows/ci.yml
Fixes Verify Files job.
In two recent PRs (https://github.com/eslint/rewrite/pull/38 & https://github.com/eslint/rewrite/pull/39), running eslint fails with:
```
Oops! Something went wrong! :(
ESLint: 9.4.0
Error: Cannot find module '/home/runner/work/rewrite/rewrite/node_modules/@eslint/config-array/dist/cjs/index.cjs'
```
I believe what happens is the following:
1. We recently released eslint v9.4.0, which is the first version that uses `@eslint/config-array`.
2. `npm install` here now installs eslint v9.4.0.
3. Since `@eslint/config-array` is in this monorepo, and the version satisfies semver range declared in `eslint`, `npm install` doesn't install `@eslint/config-array` from …
=> ci: build packages in Verify Files job

packages/migrate-config/package.json
`migrate-config` doesn't use rollup. This removes unused rollup and rollup-related dev dependencies. 
Removed `rollup` and `rollup-plugin-copy` from `packages/migrate-config/package.json`.
No.
=> chore: remove unused rollup dev dependencies

packages/compat/jsr.json
After https://github.com/eslint/rewrite/pull/28, build of the `compat` package no longer  generates `types.ts` and `types.d.ts` files in dist folders.
Removed `types.ts` and `types.d.ts` from the `include` list in `jsr.json`.
No.
=> chore: remove non-existing files from `jsr.json`

packages/migrate-config/src/migrate-config.js, packages/migrate-config/tests/fixtures/basic-eslintrc/expected.cjs, packages/migrate-config/tests/fixtures/basic-eslintrc/expected.mjs, packages/migrate-config/tests/fixtures/no-globals-for-env/expected.cjs, packages/migrate-config/tests/fixtures/no-globals-for-env/expected.mjs, packages/migrate-config/tests/fixtures/plugins-dedupe/.eslintrc.yml, packages/migrate-config/tests/fixtures/plugins-dedupe/expected.cjs, packages/migrate-config/tests/fixtures/plugins-dedupe/expected.mjs, packages/migrate-config/tests/fixtures/release-it/expected.cjs, packages/migrate-config/tests/fixtures/release-it/expected.mjs, packages/migrate-config/tests/migrate-config-cli.test.js
Fixes a bug where the same plugin referenced in `extends` and `plugins` may result in a "Cannot redefine plugin" error.
- Check `extends` before `plugins` to determine if a plugin needs to be wrapped by the compat utility.
- Added tests
=> fix: Wrap plugins that are wrapped in extends

packages/compat/package.json, packages/config-array/package.json, packages/object-schema/package.json
Add `main` and `types` entries to `package.json` files. Even though we have `exports` specified, some tools still rely on these old, top-level entries.
- Added `main` and `types` entries to `package.json` files in `compat`, `config-array`, and `object-schema`.
fixes #46
=> fix: Add 'main' and 'types' entries to package.json

.github/workflows/release-please.yml, packages/compat/README.md, packages/compat/src/fixup-rules.js, packages/compat/src/ignore-file.js, packages/compat/src/index.js, packages/compat/tests/fixtures/ignore-files/gitignore1.txt, packages/compat/tests/ignore-file.js, packages/migrate-config/package.json, packages/migrate-config/src/migrate-config.js
Add a `includeIgnoreFile()` function.
- Added `includedIgnoreFile()` function that is exported from `@eslint/compat`
- Added `convertIgnorePatternToMinimatch()` function that is exported from `@eslint/compat` (purposely undocumented because I'm not sure how end users would use this)
- Updated README for `@eslint/compat`
- Switched `@eslint/migrate-config` to use the `convertIgnorePatternToMinimatch()` function from `@eslint/compat` instead of duplicating that functionality
- Rearranged the order in which packages are released so `@eslint/migrate-config` comes after `@eslint/compat` due to the new dependency on it
Note: The `includeIgnoreFile()` function differs from the original …
=> feat: Add includeIgnoreFile() method

packages/config-array/README.md, packages/config-array/src/config-array.js, packages/config-array/tests/config-array.test.js
Fixes the bug reported in https://github.com/eslint/eslint/issues/18550.
Changed `getConfigWithStatus` to treat lone `*` as a universal pattern.
This means that files matching only `*` will be "unconfigured".
https://github.com/eslint/eslint/issues/18550
I tagged this as `fix!` because I think this should be treated as a breaking change for the config-array package.
=> fix!: treat `*` as a universal pattern

decisions/000-template.md, decisions/001-rewrite-core.md, decisions/002-javascript-jsdoc-tsc.md, decisions/003-esm.md
Formally documents decisions around this repo.
Added decision documents covering the following:
- Added a template
- To do a core rewrite
- Using JS/JSDoc/tsc instead of TypeScript
- Using ESM
I did my best to piece back together the logic from our various discussions, but do let me know if any important details are missing.
=> docs: Decision docs for start of rewrite

packages/config-array/package.json, packages/config-array/src/config-array.js, packages/config-array/tests/config-array.test.js
Allows using `\` as an escape character in patterns regardless of the operating system. In particular, on Windows.
Enabled [`allowWindowsEscape`](https://github.com/isaacs/minimatch/tree/v3.1.2?tab=readme-ov-file#allowwindowsescape) minimatch option.
refs https://github.com/eslint/eslint/issues/18597
Should this maybe be marked as a breaking change for this package?
=> fix!: Allow escaping characters on Windows

packages/migrate-config/src/migrate-config.js, packages/migrate-config/tests/fixtures/import-duplicate/.eslintrc.cjs, packages/migrate-config/tests/fixtures/import-duplicate/expected.cjs, packages/migrate-config/tests/fixtures/import-duplicate/expected.mjs, packages/migrate-config/tests/migrate-config-cli.test.js
prevent syntax error which threw by duplicate import fixupPluginRules because of multiple compat needs plugins.
- skip add fixupPluginRules when already pushed in bindings
fixes #72
=> fix: skip add plugin when already imported

.prettierignore
Ignores formatting of `jsr.json` files because `release-please` formats these files in a way that doesn't conform to prettier ([example](https://github.com/eslint/rewrite/commit/fac14b8cad5a8119dee73d2c5eec8e5f01af2a43#diff-78aacd093e79b533ecfb4ecc39dfcc0dfb1b3216415c9d1779bda2f9cc9e42bcR6-R11)).
Added `jsr.json` to `.prettierignore`.
CI failure https://github.com/eslint/rewrite/actions/runs/9684111978/job/26721093532
```
> eslint-rewrite@1.0.0 fmt:check
> prettier --check .
Checking formatting...
[warn] packages/core/jsr.json
[warn] Code style issues found in the above file. Run Prettier with --write to fix.
Error: Process completed with exit code 1.
```
=> chore: add `jsr.json` to `.prettierignore`

decisions/004-types.md
Adds a design document for the type definitions approach.
Added the design document in the designs folder.
=> docs: Add decision document around type definitions

.github/workflows/release-please.yml
Switches to the officially supported Release Please Action, which is [`googleapis/release-please-action`](https://github.com/googleapis/release-please-action). 
Updated `.github/workflows/release-please.yml` to use `googleapis/release-please-action@v4` instead of `GoogleCloudPlatform/release-please-action@v4`.
=> build: switch to `googleapis/release-please-action`

.github/workflows/release-please.yml
Publish packages with provenance
Added the --provenance flag to npm publish commands.
https://github.com/eslint/rewrite/issues/76
=> ci: Publish packages with provenance

packages/config-array/src/config-array.js, packages/config-array/tests/config-array.test.js
Fixes a bug in `ConfigArray#isDirectoryIgnored()`.
When `basePath` directory is passed in as the `directoryPath` to check, `isDirectoryIgnored()` mistakenly checks `/` against ignore patterns. Then it can match, and thus return `true`, patterns like `/` (which should be no-op/invalid as an absolute path pattern) or `**` (which is valid but should not match the `basePath` directory). 
Fixed `isDirectoryIgnored()` to always return `false` for the `basePath` directory.
refs https://github.com/eslint/eslint/issues/18706
=> fix: `basePath` directory can never be ignored

packages/migrate-config/src/compat-plugins.js, packages/migrate-config/tests/fixtures/import-duplicate/.eslintrc.cjs, packages/migrate-config/tests/fixtures/import-duplicate/expected.cjs, packages/migrate-config/tests/fixtures/import-duplicate/expected.mjs
`eslint-plugin-react` now supports ESLint v9. This PR updates `@eslint/migrate-config` to not use the compat utility with `eslint-plugin-react` in generated configs.
Removed `eslint-plugin-react` from the list of plugins that need the compat utility.
Also replaced `eslint-plugin-react` with `eslint-plugin-import` in tests that checks how migration works with two plugins that need the compat utility.
=> feat: `eslint-plugin-react` supports ESLint v9

eslint.config.js, packages/compat/package.json, packages/compat/src/fixup-rules.js, packages/core/package.json, packages/migrate-config/package.json, packages/migrate-config/src/migrate-config.js
This PR upgrades `@types/eslint` to the last version for ESLint v9. `@types/eslint` is only included in `devDependencies` which makes this change a chore, even if the eslint types are referenced in the published type declarations of `@eslint/compat` and `@eslint/migrate-config`.
* Updated the `@eslint/types` dependencies to `"^9.6.0"`.
* Updated a type import in `compat` package to work with both the v8 and v9 types.
* Replaced `Config` with `LegacyConfig` in `migrate-config` package to work with both the v8 and v9 types.
* Excluded c8-generated `coverage` directories from linting with eslint.
=> chore: upgrade `@types/eslint` to v9

eslint.config.js, package.json, packages/core/src/types.ts, packages/object-schema/src/types.ts
Enable linting for typescript files.
- Enable typescript-eslint for all ts files.
- Fixed lint errors for `no-use-before-define` rule.
- Disabled `@typescript-eslint/no-explicit-any` for some generic types.
Fix https://github.com/eslint/rewrite/issues/69
Currently `8.0.0-alpha.45` supports ESLint v9, we will need to update it later once a stable version is released.
=> chore: setup typescript-eslint

packages/config-array/src/index.js
Export `ObjectSchema` from the package. I'm working on some changes in the core where I need an instance of `ObjectSchema`, and even though the package is a dependency of `@eslint/config-array`, `@eslint/object-schema` isn't listed in `package.json`, which fails our lint check.
Exported `ObjectSchema` as a passthrough from `@eslint/object-schema`.
=> feat: Export ObjectSchema

packages/core/jsr.json, packages/core/package.json
Add CommonJS types to `@eslint/core`.
I've added a build step that copies the generated `esm/types.d.ts` file to `cjs/types.d.cts` in the `dist` directory. Updated settings so that both `dist` files will be published to npm and JSR instead of the source file. This follows the pattern we are using in other packages in this repo.
I've verified that the new `.cts` module can be imported in `@types/eslint` when `@eslint/core` is added as a dependency.
fixes #95
=> feat: add CommonJS `core` types

packages/migrate-config/README.md
Adds instructions for what to do if the default `npx` command fails.
Added mention to manually install the package if the default `npx` command fails.
Refs https://github.com/eslint/rewrite/issues/88
=> docs: Add workaround if npx fails

package.json
Ensure `.ts` files are linted on precommit
- Added `.ts` files to the `lint-staged` config in `package.json`
=> chore: Add .ts files to lint-staged

release-please-config.json
Removes hardcoded version of `@eslint/plugin-kit` from the release-please config so that the next version of this package can be released.
Updated `release-please-config.json`.
=> chore: remove `release-as` for plugin-kit

packages/core/src/types.ts, packages/plugin-kit/README.md, packages/plugin-kit/src/index.js, packages/plugin-kit/src/source-code.js, packages/plugin-kit/tests/source-code.test.js
Add `Directive` class to `@eslint/plugin-kit`. (Extracted from the core.)
- Added a `Directive` class to `@eslint/plugin-kit` to be used when implementing `SourceCode#getDisableDirectives()`
- Added a `DirectiveType` type to `@eslint/core`
- Changed `Directive#node` to be type `unknown` instead of `object` to force consumers to type cast the value before using it.
- Added tests for `Directive`
=> feat: Add Directive and DirectiveType

package.json, packages/compat/package.json, packages/compat/src/fixup-rules.js, packages/compat/src/ignore-file.js, scripts/build.js
Fix `npm run build`
- Upgraded `eslint` to the latest version to include the types fix.
- Updated the build script to honor dev dependencies as well.
=> fix: Upgrade ESLint to fix type errors

packages/core/src/types.ts
Update types.
This PR adds the `defaultLanguageOptions` as an optional property to the `Language` interface.
* Change request: eslint/eslint#18985
* PR in `eslint`: eslint/eslint#19003
=> feat: Add `Language.defaultLanguageOptions`

eslint.config.js, packages/core/package.json, packages/core/src/types.ts
Add types for rules that will work regardless of the language being used.
I added several types that let us completely type check rules. These types are as generic as possible to allow for language plugins to override or better define their types, too.
These are *not* guaranteed to match the types in `@types/eslint`, which are very specific to the JavaScript language. The intent is to define something that will work and then see if we can backport into `@types/eslint` in a way that still works with the JavaScript rules.
Does the naming make sense for the types? I tried to be more specific to avoid ambiguity (i.e., `RuleFixer` is now `RuleTextEditor`).
=> feat: Add rule types

packages/core/src/types.ts
Fix a bug in the types.
This PR fixes the type integration tests in ESLint which would currently fail with `@eslint/core@0.8.0` (eslint/eslint#19098).
The fix consists in marking the properties of generic interfaces as non-optional, meaning that they can't be `undefined`. These properties are only used to refer to a type. For example there is no actual object with a property `MessageIds`, but `RuleDefinitionTypeOptions["MessageIds"]` is used as an alias for `string`. If a union with `undefined` is desired, it can always be indicated explicitly as `RuleDefinitionTypeOptions["MessageIds"] | undefined`.
refs eslint/eslint#19098
=> fix: non-optional properties in generic interfaces

packages/core/src/types.ts
Add `normalizeLanguageOptions` to the `Language` type.
Added an optional `normalizeLanguaeOptions()` method to the `Language` type.
refs https://github.com/eslint/eslint/issues/19037
=> feat: Add Language#normalizeLanguageOptions()

.github/workflows/ci.yml, packages/core/package.json, packages/core/tests/types/tsconfig.json, packages/core/tests/types/types.test.ts
Add type tests.
Add basic type tests for the `core` package and update the CI build to run the type tests.
=> chore: add type tests for `core` package

packages/core/src/types.ts, packages/core/tests/types/types.test.ts
I realized we could easily type check `messageId` in `context.report()` if we pass through the `MessageIds` type from `RuleDefinition`, so I did that.
Enhancements to `RuleContext` and related types:
* Added `MessageIds` to `RuleContextTypeOptions` to support custom message identifiers.
* Simplified the `RuleContext` interface by using `RuleContextTypeOptions` directly.
* Updated the `report` method in `RuleContext` to include `MessageIds` in the `ViolationReport` type.
* Enhanced `ViolationMessage` and `ViolationReport` types to support custom `MessageIds`.
* Included `MessageIds` in the `RuleDefinition` context options.
Test updates:
* Added `TestMessageIds` type and included it in `TestRuleContext` to validate the changes in the test suite.
=> feat: Check messageIds in context.report()

packages/core/src/types.ts
Make compatibility changes to `RuleDefinition`
Changed `meta.replacedBy` from `string[] | undefined` to `readonly string[] | undefined` to be backwards-compatible with the definitions in `@types/eslint`.
related to https://github.com/eslint/eslint/pull/19157#issuecomment-2619837426
=> fix: Make meta.replacedBy read only

packages/core/src/types.ts, packages/core/tests/types/types.test.ts
Update the `RuleDefinition` type.
- Added `meta.docs.frozen` property
- Added the `meta.docs.deprecated` and `meta.docs.replacedBy` updates from https://github.com/eslint/eslint/pull/19238
- Updated the type tests
Refs https://github.com/eslint/eslint/pull/19238
I think it's okay to merge in the deprecation changes before https://github.com/eslint/eslint/pull/19238, as the types here will apply to all plugins first and later be adopted by the core.
=> feat: Update RuleDefinition for frozen and deprecations

packages/core/src/types.ts, packages/core/tests/types/types.test.ts
Adds `defaultOptions` to `RulesMeta` in `@eslint/core` types. 
Copied this:
https://github.com/eslint/eslint/blob/758c66bc8d83cd4eda9639b0745f0d0fb70f04f4/lib/types/index.d.ts#L744-L745
Also added `schema`, `defaultOptions`, and `context.options` in tests.
https://github.com/eslint/eslint/pull/17656
=> feat: Update RuleDefinition with `meta.defaultOptions`

.github/workflows/release-please.yml, scripts/build.js, scripts/publish.js, scripts/shared.js
Add a new script to simplify publishing packages.
Added a new script that automatically calculates the correct publish order for packages in this repo. It also posts to social media once complete.
All npm packages are published first, followed by all JSR packages.
This should simplify publishing going forward and allow us to simplify the `release-please.yml` workflow.
For now, I've added this into `release-please.yml` in dry run mode so it just output the commands that it would otherwise execute. I figured we can do this for a couple of releases to ensure that the commands its intends to run are correct before switching over.
=> chore: Add publish script

packages/config-helpers/README.md, packages/config-helpers/package.json, packages/config-helpers/src/global-ignores.js, packages/config-helpers/src/index.js, packages/config-helpers/tests/global-ignores.test.js, packages/config-helpers/tests/index.test.js, packages/config-helpers/tests/types/types.test.ts
Added a `globalIgnores()` function
This pull request introduces the `globalIgnores` function to the `config-helpers` package, allowing users to specify patterns for files and directories that should be globally ignored by ESLint. The most important changes include the addition of this new function, updates to the documentation, and corresponding tests.
* Added `globalIgnores` function in `packages/config-helpers/src/global-ignores.js` to create a global ignores config with specified patterns.
* Exported `globalIgnores` function in `packages/config-helpers/src/index.js`.
* Updated `packages/config-helpers/README.md` to include a section on the `globalIgnores` function, with an example usage.
* Added a new build script `build:dedupe-types` in `packages/config-helpers/package.json` to …
=> feat: Add globalIgnores helper function

packages/config-helpers/src/define-config.js, packages/config-helpers/tests/define-config.test.js
Update `defineConfig()` to search for flat configs in plugins when a string is used in `extends`.
- Updated `defineConfig()` so it `"plugin/config"` is eslintrc, then it search for `"plugin/flat/config"`. It throws an error if that config isn't found or is also eslintrc.
- Added tests.
Refs https://github.com/eslint/eslint/issues/19513
=> feat: Look up flat/ config alternatives in defineConfig

packages/config-array/src/config-array.js, packages/config-array/tests/config-array.test.js
Addresses issue where patterns starting with "./" were not correctly matched in `files` and `ignores`.
Strip "./" from the start of strings in `files` and `ignores` so that they match as expected.
https://github.com/eslint/eslint/issues/18757
=> feat: normalize patterns to handle "./" prefix in files and ignores

packages/config-array/tests/config-array.test.js
Fixes error message checking in several config-array tests.
* Fixed `testValidationError` helper function to treat `expectedError` argument as a regex that should be passed to `assert.throws()` as that's how it is used in the tests.
* Updated two calls to pass a regex because strings don't really check error messages.
* Simplified checks for `configArray.normalize()` to use `assert.rejects()`.
=> test: fix error message checking

packages/core/src/types.ts, packages/core/tests/types/types.test.ts
I realized that `defaultOptions` can be assigned the same type as the rule options for rules to allow for better type validation.
- Updated the `RulesMeta` to accept `RuleOptions` as an argument
- Updated `defaultOptions` to be the same type as `RuleOptions`
=> feat: Set type for RuleDefinition.defaultOptions

package.json, packages/core/package.json, packages/core/src/types.ts, packages/core/tests/types/tsconfig.json, packages/core/tests/types/types.test.ts
fix #177
Updated `@eslint/core`:
* Added types `CustomRuleTypeDefinitions` and `CustomRuleDefinitionType` and updated tests.
* Added options to the test TS config to make the tests stricter.
* Updated `package.json` to use the latest TypeScript version.
* Removed unused dev dependency `json-schema` since only `@types/json-schema` is required.
=> feat: add core types for language-specific rule definitions

packages/core/src/types.ts, packages/plugin-kit/src/source-code.js, packages/plugin-kit/tests/types/types.test.ts
Hello,
This PR addresses issue https://github.com/eslint/markdown/issues/341.
I exported `SourceCodeBaseTypeOptions` from `@eslint/core` and used it.
I also added tests to validate the changes.
Let me know if there's anything else I should do!
fixes https://github.com/eslint/markdown/issues/341
=> feat: make `TextSourceCodeBase` a generic type

release-please-config.json
Fix the title of release-please PRs.
It seems that eslint-github-bot doesn't like the default title of pull requests created by release-please with the `"separate-pull-requests": true` setting (e.g. #187). This PR fixes the title format by removing the branch name after the tag.
Before:
> chore(main): release core 0.14.0
After:
> chore: release core 0.14.0
#183
=> chore: fix release-please PR title

packages/core/package.json
Added `json-schema` as a dev dependency to `@eslint/core`. This is needed in order to satisfy JSR's publish requirements.
=> build: Fix JSR publish for eslint/core

package.json, packages/compat/package.json, packages/config-helpers/package.json, packages/config-helpers/src/define-config.js, packages/migrate-config/package.json, templates/package/package.json
As of ESLint v9.26.0, `Plugin.meta` type has the `namespace` property (https://github.com/eslint/eslint/commit/9736d5d15870c9185da7d140becb9a15aa69057d).
This removes an now-unnecessary `@ts-ignore` comment and bumps eslint to v9.27.0 in dev dependencies in all projects.
Removed the mentioned `@ts-ignore` comment and updated package.json files.
=> chore: remove unused `@ts-ignore` comment

packages/config-array/src/config-array.js, packages/config-helpers/src/define-config.js, packages/config-helpers/src/global-ignores.js, packages/object-schema/src/object-schema.js, packages/plugin-kit/src/source-code.js
Hello,
In this PR, I've updated and fix incorrect error types in JSDoc comments for better clarity.
I've updated and fix error types in JSDoc comments for better clarity.
Refs: https://github.com/eslint/rewrite/pull/211#discussion_r2107213406
=> refactor: update and fix error types in JSDoc comments

.github/workflows/bun-test.yml, .gitignore, packages/config-array/tests/config-array.test.js
Add Bun CI testing
- Added GitHub workflow to run Bun
- Made a small modification to a test in `config-array` because Bun has a different error message than in Node.js
=> ci: Test in Bun

packages/config-array/src/config-array.js, packages/config-array/tests/config-array.test.js
Fixes the problem described in https://github.com/eslint/eslint/issues/19814.
Fixed the code that checks for explicit matches in `files` to account for array elements of `files`.
https://github.com/eslint/eslint/issues/19814
=> fix: explicit match in array elements of `files`

eslint.config.js, packages/core/src/types.ts, packages/core/tests/types/types.test.ts
Adds interfaces for `settings` and `rules` can be extended by plugins.
- Added `SettingsConfig` interface
- Added `RulesConfig` interface
- Updated `LinterOptionsConfig` interface (for completeness)
- Updated types tests
fixes #208
Just a note that once this is released, we'll need to update the `Config` type in the `eslint` package.
=> feat: Add extendable config types

packages/config-array/src/config-array.js, packages/config-array/tests/config-array.test.js
Fixes the problem described in https://github.com/eslint/eslint/issues/19813.
Updated regex pattern that checks for universal patterns to treat negated patterns as such.
https://github.com/eslint/eslint/issues/19813
=> fix: consider negated patterns universal

packages/core/src/types.ts, packages/core/tests/types/types.test.ts
To allow rule configs to have an array with just a severity:
```js
{
rules: {
semi: ["error"]
}
}
```
- Updated `RuleConfig` to also match `[Severity]`.
- Updated types tests to verify this change.
Split from https://github.com/eslint/eslint/pull/19843#discussion_r2142999877
=> fix: Allow RuleConfig to have array with just severity

packages/compat/package.json
Updated to the suggestion in https://github.com/eslint/rewrite/pull/106#issuecomment-2525696320. This was a breaking change, causing a refresh of our lockfile to generate the following error:
```
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies
XXX
└─┬ @eslint/compat 1.2.9
└── ✕ unmet peer eslint@^9.10.0: found 8.57.0
```
This resolves the breaking change, since I believe @eslint/compat was introduced during the v8 eslint cycle and we don't need to go lower.
To resolve a breaking change in @eslint/compat.
Added eslint v8 to the peer dependencies.
https://github.com/eslint/rewrite/pull/106#issuecomment-2525696320
=> fix: relax `@eslint/compat` eslint peerDependencies constraint

packages/plugin-kit/src/config-comment-parser.js, packages/plugin-kit/tests/config-comment-parser.test.js
Improve regular expressions in this repository that could match with unexpected overhead for certain strings.
I improved a regular expression in the plugin-kit package that could match in quadratic runtime for certain strings. I did not find any other regular expressions in the source code of this repository that could have this kind of impact.
n/a
no
=> fix: potential quadratic runtime in regular expression

packages/compat/README.md, templates/package/README.md
In this PR, I've corrected the Bun installation command and updated the `README.md` to use the `defineConfig` helper function.
This is a straightforward documentation update.
I've corrected the Bun installation command and updated the `README.md` to use the `defineConfig` helper function.
N/A
N/A
=> docs: correct bun installation command and use `defineConfig` in README

package.json
In this PR, I've fixed CI to work around a failure on Windows with Bun.
Currently, Bun CI on Windows is failing due to the newly released Rollup `4.52.0`. 
As a workaround, I've pinned Rollup to `4.51.0`.
Here are the references:
- Release: https://github.com/rollup/rollup/releases/tag/v4.52.0
- Issue: https://github.com/rollup/rollup/issues/6119
- PR: https://github.com/oven-sh/bun/pull/22816
https://github.com/eslint/rewrite/actions/runs/17956574548/job/51069303147
In this PR, I've fixed CI to work around a failure on Windows with Bun.
Ref: https://github.com/eslint/json/pull/154#discussion_r2368479671
It seems that `rollup` 4.52.2 has been released, but the issue above wasn't included, so I think we need to wait until `rollup` 4.53.0 is released. …
=> ci: workaround for CI failure on Windows with Bun

packages/plugin-kit/tests/source-code.test.js
This PR is follow-up to https://github.com/eslint/css/pull/167#discussion_r2372668738, and https://github.com/eslint/json/pull/109#discussion_r2372609361.
In this PR, I've used `strictEqual` in `plugin-kit` where possible.
In this PR, I've used `strictEqual` in `plugin-kit` where possible.
Ref: https://github.com/eslint/css/pull/167#discussion_r2372668738, and https://github.com/eslint/json/pull/109#discussion_r2372609361
N/A
=> test: use `strictEqual` in `plugin-kit` where possible
